@startuml

card "PracticeSetting" as ps
card "DKGeV: Fachabteilungen (BPflV)" as fachabt
card "DKGeV: erweiterte Fachabteilungen (BPflV)" as fachabterw

ps --> fachabt : [[ConceptMap-IheCsFachrichtungAerztlich2BPflV.html Map]]
ps --> fachabterw : [[ConceptMap-IheCsFachrichtungAerztlich2BPflVerw.html Map]]

fachabt --> ps : [[ConceptMap-BPflV2IheCsFachrichtungAerztlich.html Map]]
fachabterw --> ps : [[ConceptMap-BPflVerw2IheCsFachrichtungAerztlich.html Map]]

@enduml